name: Hugo Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: npm install, build, and test
      run: |
        npm install
        npm build
      env:
        CI: true

    - name: Build the site in the hugo container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/hugo \
        -w /srv/hugo \
        kujenga/hugo:v0.78.2-1 hugo

    - uses: actions/upload-artifact@v1
      with:
        name: static-dist
        path: app/public
